version: '3.8'

services:
  youtube-transcript-api:
    build: .
    expose:
      - '5000'
    environment:
      - NODE_ENV=production
      - PORT=5000
      - API_KEY=${API_KEY:?}
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://localhost:5000/live',
        ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    restart: unless-stopped
